<?php

namespace Eduance\Structural\Decorator\Example;

class EncryptionDecorator extends DataSourceDecorator
{
    public function writeData($data)
    {
        parent::writeData($data); // TODO: Change the autogenerated stub
    }

    public function readData()
    {
        // encrypt...
        return parent::readData(); // TODO: Change the autogenerated stub
    }
}